
export enum CallStatus {
  IDLE = 'IDLE',
  CREATING_ROOM = 'CREATING_ROOM',
  WAITING = 'WAITING',
  JOINING = 'JOINING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR',
}
